MedicalChatbot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chatbot/', include('symptoms.urls')),
    path('', RedirectView.as_view(url='chatbot/'))
]

symptoms/urls.py
from django.urls import path
from . import views

app_name = 'symptoms'

urlpatterns = [
    path('', views.home, name='home')
]

symptoms/models.py
from django.db import models

# Create your models here.

symptoms/views.py
from django.shortcuts import render

# Create your views here.

# list of symptoms
symptoms = []


# THIS IS THE DUMMY FUNCTION
# This function is taking the list of symptoms user in taking as input and then processing it
# TODO: REPLACE THIS FUNCTION WITH YOUR DRIVER CODE

def process_symptoms(symptoms_list):
    return [f'I am loving {symptom}' for symptom in symptoms_list]


def home(request):
    # just for searching the data and appending them in the current list of items
    # when request method is GET
    if request.method == 'GET':
        if 'user-symptoms' in request.GET:
            current_symptom = request.GET['user-symptoms']
            if current_symptom not in symptoms:
                symptoms.append(current_symptom)
        context = {
            'symptoms': symptoms
        }
        return render(request, 'symptoms/index.html', context=context)
    # when I am sending post data, I should not display the sensitive information on the address bar
    # when request method is POST
    else:
        context = {
            'symptoms': symptoms
        }
        if len(symptoms) < 3:
            list_underflow = "Please enter at least 3 symptoms for proper prediction"
            context['list_underflow'] = list_underflow
        else:
            predicted_diseases = process_symptoms(symptoms)
            # symptoms.clear()
            context['predicted_diseases'] = predicted_diseases
        return render(request, 'symptoms/index.html', context=context)

templates/symptoms/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MedicalChatbot</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <link rel="stylesheet" href="{% static 'assets/fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="{% static 'assets/css/Bold-BS4-Footer-Big-Logo.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Community-ChatComments.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/footer-ultimate.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Pretty-Search-Form.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Social-Icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">

    <style>
        .output-style {
            max-width: 80%;
            margin: 20px auto;
            padding: 20px;
            min-height: 20vh;
            background: rgba(255, 255, 255, 0.8);
        }

        .symptoms-container {
            padding: 20px;
            width: 100%;
        }

        .diseases-container {
            padding: 20px;
            width: 100%;
        }
    </style>
</head>

<body>
<nav class="navbar navbar-light navbar-expand-md">
    <div class="container-fluid"><a class="navbar-brand" href="#">Medical Chatbot</a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse"
             id="navcol-1">
            <ul class="nav navbar-nav ml-auto"></ul>
            <ul class="nav navbar-nav">
                <li class="nav-item" role="presentation"><a class="nav-link active"
                                                            href="#"><strong>Description</strong></a></li>
            </ul>
        </div>
    </div>
</nav>
<div id="promo">
    <div class="jumbotron">
        <h1><strong>What are your main symptoms ?</strong><br></h1>
        <p><br><strong>Symptom Checker :&nbsp;</strong>Identify possible conditions related to your symptoms.<br></p>
        <p></p>
        <form class="search-form" action="{% url 'symptoms:home' %}" method="get">
            <div class="input-group">
                <div class="input-group-prepend"><span class="input-group-text"><i class="fa fa-search"></i></span>
                </div>
                <input class="form-control" type="text" placeholder="Enter your probable symptoms.."
                       name="user-symptoms">
                <div class="input-group-append">
                    <button class="btn btn-light" type="submit">ADD</button>
                </div>
            </div>
        </form>
        <div class="row">
            <div class="symptoms-container col-md-4">
                {% if symptoms %}
                <ul class="list-group">
                    {% for symptom in symptoms %}
                        <li class="list-group-item"><span>{{ symptom | upper }}</span></li>
                    {% endfor %}
                </ul>
            {% elif predicted_diseases %}
                <p>Here are your predicted results.. Enjoy</p>
            {% else %}
                <p>Search for symptoms for processing the data</p>
            {% endif %}
            </div>
            <div class="diseases-container col-md-8">
                {# this will print out all the symptoms that are processed by the backend #}
                {% if list_underflow %}
                    <p>{{ list_underflow }}</p>
                {% elif predicted_diseases %}
                    <ul class="list-group" style="max-width: 70% !important; margin: 0 auto">
                        {% for disease in predicted_diseases %}
                            <li class="list-group-item"><span>{{ disease }}</span></li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>Once you have searched for symptoms click here and see the magic unfold!!</p>
                    <small><em>More the symptoms you enter more are the chances of correct prediction!!</em></small>
                {% endif %}
            </div>
            <br>
            <br>
            <div class="col text-center">
                <form method="post" action="{% url 'symptoms:home' %}">
                {% csrf_token %}
                <input type="hidden" name="process-symptoms">
                    <button id="demo" type="submit" class="btn btn-default">Click me</button>
            </form>
            </div>
        </div>
</div>
</div>
<div class="container-fluid" style="background: black">
    <div id="footer">
        <footer id="footer">

            <div style="background: black; text-align: center; margin: 0; padding:30px; width: 100%;">
                <p style="color:grey; font-family: raleway, sans-serif">Copyright (c) 2019 MedicalChatbot.in</p>
            </div>
        </footer>
    </div>
</div>
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>